import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '@/public/assets/scss/style.scss';

const PoppinsFont = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--poppins-font',
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Faq',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${PoppinsFont.variable}`}>{children}</body>
    </html>
  );
}
